### ISSUE TITLE
Why 250 and not 1000?

### ISSUE THREAD

**Issue by idoaflalo** [fufar/simple-clock-card#1]
https://github.com/fufar/simple-clock-card/blob/ab8f49ad5075de337175b3bb6d1d9587002e5923/simple-clock-card.js#L53

**Comment by fufar** [comment]
why not, it cause problem?

**Comment by idoaflalo** [comment]
It's better to update the DOM as little as possible.
If it was the only process on the page I would say it does not affect, but because lovelace can be heavy I think it is better to update every second (Which is the smallest unit the clock displays).

**Comment by fufar** [comment]
changed to 1000ms
