### ISSUE TITLE
Doesn't appear in integrations

### ISSUE THREAD

**Issue by Philou06** [fufar/simple-clock-card#10]
Hi, thx for that but sadly doesn't work for me, have done the first step to install it in HACS but doesn't appear in integrations as explained, any idea?

![image](https://user-images.githubusercontent.com/81933852/115568549-b211e280-a2bc-11eb-93b2-7c1423ff4e05.png)
![image](https://user-images.githubusercontent.com/81933852/115568586-bb02b400-a2bc-11eb-8e7f-66bc6a21c8d8.png)

**Comment by fufar** [comment]
clear cache mb, it usally problem with it

**Comment by Philou06** [comment]
What do you mean by cache mb?

**Comment by fufar** [comment]
Try to clear your browser cache 
for some browsers you can see how to do it here https://appuals.com/how-to-clear-cache-for-one-site/

**Comment by Philou06** [comment]
I did that, still doesn't work

**Comment by fufar** [comment]
did you see that card in config-lovelace-resourses? 
and did you edit lovelace in yaml mode?

**Comment by Philou06** [comment]
Yes and yes, now I have updated to your latest version it works! Thx
