### ISSUE TITLE
12:00 PM showing as 0:00 PM

### ISSUE THREAD

**Issue by kreene1987** [fufar/simple-clock-card#12]
![image](https://user-images.githubusercontent.com/21197497/116444264-2e0aae00-a81a-11eb-8737-bd3895c55b4f.png)

Here is my config:

type: 'custom:simple-clock-card'
use_military: false
hide_seconds: true
font_size: 4rem
padding_size: 50px

**Comment by kreene1987** [comment]
Even the cover sheet shows this occuring. Non-mil time should be 12:00 PM (noon) and 12:00 AM (midnight).

**Comment by fufar** [comment]
it gets time in 24h format and then
if hour less 12 make AM
if hour more 12 make PM

how it should be done?

**Comment by kreene1987** [comment]
If greater than 12, subtract 12. So essentially 13:00:00 is 01:00:00 PM.

**Comment by cfacer** [comment]
@fufar - Ran across this issue as well today while adding to my lovelace dashboard and hopefully the information below will help demystify the 24 -> 12 hr conversion.


Military Time             12 Hour Time
-------------             -------------
00:00                         12:00 AM
00:05                         12:05 AM
01:00                          1:00AM
11:59                           11:59 AM
12:00                          12:00 PM
12:01                           12:01 PM
13:00                           1:00 PM
23:59                          11:59 PM
00:00                         12:00 AM

**Comment by krupaldesai** [comment]
@fufar thanks for this great add-on! I have just opened a PR for this fix: https://github.com/fufar/simple-clock-card/pull/14

**Comment by fufar** [comment]
@kreene1987 @cfacer check pls

**Comment by kreene1987** [comment]
Validated equation in excel:

![image](https://user-images.githubusercontent.com/21197497/118978514-0ac8af80-b93d-11eb-9af8-7888ac9a7359.png)

Looks solid to me.

**Comment by fufar** [comment]
ok. i will test for a day, if all ok  - merge tomorrow

**Comment by fufar** [comment]
merged and released 1.5
