### ISSUE TITLE
How to show different time-zones

### ISSUE THREAD

**Issue by trytogetme85** [fufar/simple-clock-card#13]
Hi there, as my question is above... how do i Show a different time zone than mine?

**Comment by fufar** [comment]
This addon does not have this feature

**Comment by DutchJaFO** [comment]
I like the simplicity of this card and I'm not sure if this would keep it 'simple'.

An offset could work, but it wouldn't account for a differnt daylight saving time from your 'home' zone (never mind countries within the same offset using a different daylight savings standard ... ). 

I don't know enough of javascript and the features available in HA/HACS to know if a good solution is possible without adding 3rd party dependencies like the moment.js library ( https://momentjs.com/ ) or  date-fns ( https://date-fns.org/ ) or whatever else is out there in open source format. I do know that time/date conversions are a can of worms you don't want to open if you can avoid it.

**Comment by fufar** [comment]
ok, if anyone make pr - i will merge
for now close this issue
