### ISSUE TITLE
Better padding and sizing.

### ISSUE THREAD

**Issue by spencerthayer** [fufar/simple-clock-card#18]
This add-on needs padding for each CSS selector: top, bottom, left, and right. How do we control these settings given the current code?

**Comment by fufar** [comment]
Im not js developer, so maybe doesnt understand question right
now this things not controled (maybe they are default?)

**Comment by walkercz** [comment]
It should be enough to:

replace in 
/config/www/community/simple-clock-card/simple-clock-card.js

//this.content.style.padding = this.config.padding_size ? this.config.padding_size : '200px' ;
			this.content.style.paddingLeft = this.config.paddingLeft_size ? this.config.paddingLeft_size : '0px';
			this.content.style.paddingRight = this.config.paddingRight_size ? this.config.paddingRight_size : '0px';
			this.content.style.paddingTop = this.config.paddingTop_size ? this.config.paddingTop_size : '60px';
			this.content.style.paddingBottom = this.config.paddingBottom_size ? this.config.paddingBottom_size : '60px';

then use paddingLeft_size etc. in yaml

**Comment by fufar** [comment]
Can you make pr for this feature? @walkercz

**Comment by fufar** [comment]
added in https://github.com/fufar/simple-clock-card/releases/tag/1.6
