### ISSUE TITLE
Show local instead of device timezone

### ISSUE THREAD

**Issue by pafnow** [fufar/simple-clock-card#19]
When traveling abroard and accessing HA this widget shows the clock in the device timezone, not the local HA one.
Could we add a configuration option to always show the local timezone ?

**Comment by fufar** [comment]
I think this addon purpose is wall panel or something simular, not for use as "world clock"

**Comment by ChristophCaina** [comment]
I still think it would make sense.
Sure - there is the option to use your dashboard on a Wall panel, where it does not hurt if the time zone of your server will be used...

But: I can also use the app on my mobile phone - and there, it would be great, if the dashboard does also show the local time.
The purpose of the card is to provide a 'nice looking' Clock - so it is "user-information" about the time.
I don't care about the time of my server...

If I want to have an information about the servers time, I'll add a row in an entity card for the server-monitoring ;)
