### ISSUE TITLE
Mis-labeled options

### ISSUE THREAD

**Issue by wklink** [fufar/simple-clock-card#2]
I really like this clock, but I think the option for "use_military" is mis-labeled.  The military uses as 24 hour clock instead of AM/PM, so I would have expected `use_military: true` would disable AM/PM.  Also, AM/PM clocks should show "12" (AM or PM), instead of "0".

**Comment by robertwigley** [comment]
I agree with the above. I expected `use_military: true` to use the 24-hour clock.

**Comment by fufar** [comment]
try 1.2 version - don't forget to clear cache after update

**Comment by fufar** [comment]
seems to be ok - if not write here
