### ISSUE TITLE
Possible to select time zone?

### ISSUE THREAD

**Issue by GeekDoc** [fufar/simple-clock-card#26]
I'm using simple-card-clock on my wall tablets and really liking it.
Now, I'm creating a dashboard for my office screen.  If simple-card-clock offered a time zone option, I could use multiple to show time zones of my team.
Thank you for consideration.

**Comment by fufar** [comment]
For me  addon purpose is wall panel or something simular, for home, not for use as "world clock", but if you want this feature - you can make a PR and i will merge it. I think in this case default setting must be like now local time
