### ISSUE TITLE
use_military does not show leading zeros.

### ISSUE THREAD

**Issue by GeekDoc** [fufar/simple-clock-card#27]
The 24-hour format option works fine, but I was expecting military time, which always has two digits for the hour (e.g. "09:00").
Could a leading zero option be added?

**Comment by GeekDoc** [comment]
I haven't done any coding for HA, but it looks like changing line 44 to:
    let time_str =  (use_military ? addZero(h) : ((h + 11) % 12) + 1 ) +
would always add the zero.  Adding the option would obviously take a bit more.  If I get some time to figure this out, I'll do a PR.

**Comment by GeekDoc** [comment]
Submitted pull request.

**Comment by fufar** [comment]
merged in v1.7 @GeekDoc
