### ISSUE TITLE
Does not work on android app on older devices

### ISSUE THREAD

**Issue by Silvered87** [fufar/simple-clock-card#29]
I want to use simple clock card on my old tablet na a wall. However on the card it says "Custom element doesn't exist: simple-clock-card". On my phone and pc it works withoout any problems

**Comment by fufar** [comment]
May be tablet to slow to work as panel in ha? I use Galaxy Tab A 8.0 SM-T355 (2015) on android 7 in HA android app, and it works fine

**Comment by Silvered87** [comment]
I already resolved the issue. All it took was hard reset of device. I think
that android is loading something at full reboot that is not loaded
otherwise.

czw., 4 maj 2023, 09:49 użytkownik fufar ***@***.***> napisał:
