### ISSUE TITLE
Font Size Option

### ISSUE THREAD

**Issue by robertwigley** [fufar/simple-clock-card#3]
Please consider adding a small enhancement to be able to change the font size in the options. It would be nice to be able to decrease the size of the font to allow a bit more padding around it and the card.

**Comment by Rapace29** [comment]
**Thank's for your work.**  
Would it be able to consider adding  an icon, date (month an day) in french, bold, change policy size, color, ... ?

**Comment by fufar** [comment]
> **Thank's for your work.**
> Would it be able to consider adding an icon, date (month an day) in french, bold, change policy size, color, ... ?

No, I'm cant write on js, so if anyone can add it through PR - i will add, my limits will end on font size :)

**Comment by fufar** [comment]
added in 1.3
