### ISSUE TITLE
throws error "Cannot add property use_military"

### ISSUE THREAD

**Issue by elitehammer** [fufar/simple-clock-card#4]
Hi,
I have added a repository via the HACS store (should be updated installation options). Restarted HA then, tried to add into the Lovelace the manual card with:

`type: 'custom:simple-clock-card'`

I received the following error message:

```
Cannot add property use_military, object is not extensible
type: 'custom:simple-clock-card'
```
is there something I did wrong or there is an error in the script?

I am running Home Assistant 2021.3.4

**Comment by fufar** [comment]
show  full lovelace card code
try to copy this, will it work?
```
type: 'custom:simple-clock-card'
use_military: false
hide_seconds: false
```

**Comment by fufar** [comment]
hope it ok now :)

**Comment by elitehammer** [comment]
Thanks, @fufar it started to work after an update. I have tried the same code as well before an update.
Love minimalistic look :)
